name = "Mongeese 4 Client"
author = "Max Caplan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a897c921518e31124c4579694ffa64dcd70c23f1da7af58c09c655ebec34966e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
