name = "Mongeese 4 Client Lite"
author = "Max Caplan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "440815fc60535f6f7058db08733580223a8725942f884c59886aabc6a2087289"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
